### ISSUE TITLE
Crash Reports - Tried to call `FileSystemPane.microbit_fs` (`MicroPythonDeviceFileList`) after deletion

### ISSUE THREAD

**Issue by AlanLL** [mu-editor/crash-reports#185]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_GB
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Alan_\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 750, in on_ls_fail
    self.disable()
  File "C:\Users\Alan_\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 689, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```

**Comment by carlosperate** [comment]
Hi everyone,

I believe this issue has been fixed already, but we haven't done a release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">

**Comment by carlosperate** [comment]
Thanks for the report @AlanLL and all your help debugging this issue!

The new Mu Editor v1.2.0 released yesterday fixes this issue, if you download the latest installer for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be able to look into that issue 👍

Thanks again!
