### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fadlifr** [mu-editor/crash-reports#191]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_ID
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Fadli Faturrahman R\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 299, in installed
    next(iterlines)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fadli Faturrahman R\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 1405, in show_admin
    baseline_packages, user_packages = venv.installed_packages()
  File "C:\Users\Fadli Faturrahman R\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 720, in installed_packages
    for package, version in self.pip.installed():
  File "C:\Users\Fadli Faturrahman R\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 305, in installed
    raise VirtualEnvironmentError("Unable to parse installed packages")
mu.virtual_environment.VirtualEnvironmentError: Unable to parse installed packages

```

**Comment by fadlifr** [comment]
i don't understand why it can not work

**Comment by carlosperate** [comment]
Hi @fadlifr,

You are using an old version of Mu, could you install the latest version and try again?
