### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by goder7015** [mu-editor/crash-reports#197]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: zh_TW
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\user\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\user\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 627, in ensure_and_create
    self.ensure()
  File "C:\Users\user\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 665, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\user\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 732, in ensure_interpreter_version
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Mu interpreter at version 38; venv interpreter at version ï¿½Ï¥Î¤ï¿½ï¿½ï¿½ï¿½rï¿½Xï¿½ï¿½: 950
38.

```
[mu.log](https://github.com/mu-editor/crash-reports/files/8967917/mu.log)

**Comment by carlosperate** [comment]
Thanks for the report and the log @goder7015 !

Could you run the following command in a command prompt and paste the result in a response here? It'd be really useful to understand the issue:

```
C:\Users\user\AppData\Local\python\mu\mu_venv-38-20220623-215059.FAILED\scripts\python.exe -c "import sys; print('%s%s' % sys.version_info[:2])"
```

Thanks!

**Comment by goder7015** [comment]
It just left a number 38 and  a blank line.

**Comment by carlosperate** [comment]
Thanks @goder7015, that's really useful, as it is exactly what I would expect.

The issue seems to be that when Mu runs the same command it gets this:
```
�ϥΤ����r�X��: 950

38.
```

I'm guessing the weird characters are an issue in Mu encoding-decoding text encoded in your PC's locale (is that Chinese Taiwanese?). Do you know what the default encoding of your default shell is? Have you configured your default shell in any way different than the default?

The thing is that with this command we would not expect any other text to be returned other than `38`, so I'm wondering if the rest of the text might be added by your shell? Any information you could provide would be really useful to try to ping this down.
