### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mlmiller751** [mu-editor/crash-reports#201]
Unable to attach log file, but Pico on M1x Mac (12/21) 16" MBP unable to install Mu, seems like file system incompatibility with APFS or some security setting (tried the obvious).

Unable to consistently access serial port using screen command from Terminal (works first time only).

PICO

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 x86_64

```
AB18/d/Mu Editor.app/Contents/Resources/Python/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mlmiller/Library/Application Support/virtualenv/wheel/house/setuptools-62.3.4-py3-none-any.whl'
Traceback (most recent call last):
  File "/private/var/folders/09/73yh56190_vd9w6kxgh4q7rw0000gn/T/AppTranslocation/0D6A82F3-4BCA-42D4-8DD4-87FC5DCBAB18/d/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 56, in _install
    installer.build_image()
  File "/private/var/folders/09/73yh56190_vd9w6kxgh4q7rw0000gn/T/AppTranslocation/0D6A82F3-4BCA-42D4-8DD4-87FC5DCBAB18/d/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 50, in build_image
    with zipfile.ZipFile(str(self._wheel)) as zip_ref:
  File "/private/var/folders/09/73yh56190_vd9w6kxgh4q7rw0000gn/T/AppTranslocation/0D6A82F3-4BCA-42D4-8DD4-87FC5DCBAB18/d/Mu Editor.app/Contents/Resources/Python/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mlmiller/Library/Application Support/virtualenv/wheel/house/pip-22.1.2-py3-none-any.whl'

```

**Comment by carlosperate** [comment]
Thanks for the report @mlmiller751.
If you are unable to attach the file to this GitHub thread, would you be able to copy and paste the contents here?
Thanks!

**Comment by carlosperate** [comment]
Superseded by https://github.com/mu-editor/crash-reports/issues/202
