### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ritamgit-alt** [mu-editor/crash-reports#209]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_IN
Platform: Windows 10 10.0.18363 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 349, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 809, in setup
    os.makedirs(wd)
  File "C:\Users\Ritam Debnath\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Ritam Debnath\\mu_code'

```

**Comment by carlosperate** [comment]
Thanks for the report @ritamgit-alt!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\Ritam Debnath\AppData\Local\python\mu\Logs\mu.log`

**Comment by ritamgit-alt** [comment]
Yeah sure

**Comment by ritamgit-alt** [comment]
[mu.log.txt](https://github.com/mu-editor/crash-reports/files/9041657/mu.log.txt)

**Comment by ritamgit-alt** [comment]
that all I got

**Comment by carlosperate** [comment]
Thanks for the log @ritamgit-alt, that was really useful!

Looking at the log entries, they are duplicated, which makes me believe that there were perhaps 2 instances of Mu running in parallel and racing each other at creating these directories, as described in:
- https://github.com/mu-editor/mu/issues/1755

If you try to run Mu again, and ensure it is only running once, do you still get this problem?

**Comment by ritamgit-alt** [comment]
thanks for the  helping there’s no issue now

**Comment by carlosperate** [comment]
Thanks for the update @ritamgit-alt, as we are tracking this issue in https://github.com/mu-editor/mu/issues/1755 I'll close this Crash Report.
