### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cynovg** [mu-editor/crash-reports#22]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: ru_RU
Platform: Linux 5.4.0-99-generic mu-editor/mu#112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @cynovg 
Were you able to resolve with issue with Mu with the steps listed in my last message?
