### ISSUE TITLE
Crash Report Debian10 RADXA ZERO ARM64

### ISSUE THREAD

**Issue by 6SwC** [mu-editor/crash-reports#220]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: C
Platform: Linux 5.10.69-12-amlogic-g98700611d064 #amlogic SMP PREEMPT Tue Jun 14 12:47:53 UTC 2022 aarch64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 178, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 149, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.7/zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.1.zip'

```

**Comment by carlosperate** [comment]
Thanks for the report @6SwC !

Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `~/.cache/mu/`

Is it possible you've installed Mu in the system Python using sudo? In that case you might need sudo as well to run it.

It's recommended to install Mu in a virtual environment, I personaly recommend even using something like [pipx](https://pypa.github.io/pipx/), that way you can avoid issues like this one.

**Comment by 6SwC** [comment]
Carlos, 

Mu was installed using sudo su, pip install mu, I am executing the Mu editor with su account.  I have not tried running Mu from command line in terminal.

**Comment by carlosperate** [comment]
>  I am executing the Mu editor with su account. I have not tried running Mu from command line in terminal.

How are you launching Mu if it's not from the terminal?

If you can install Mu in a virtual environment without sudo it should work.

**Comment by 6SwC** [comment]
I am executing it from the applications menu in Debian 10 buster using a su account as root. On Jul 8, 2022 6:01 AM, Carlos Pereira Atencio ***@***.***> wrote:

I am executing the Mu editor with su account. I have not tried running Mu from command line in terminal.

How are you launching Mu if it's not from the terminal?
If you can install Mu in a virtual environment without sudo it should work.

**Comment by carlosperate** [comment]
Sorry, I don't use Linux as my main OS and I'm not sure I understand. If you installed Mu with pip how did it end up in the Debian applications menu?

If you can install Mu in a virtual environment, it should resolve your issue.
