### ISSUE TITLE
Failed to install Jedi wheel during load

### ISSUE THREAD

**Issue by tonybaloney** [mu-editor/crash-reports#229]
Version: 1.1.1
Locale: en_GB
Platform: Windows 10 10.0.22621 AMD64

```
baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 921, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 295, in install
    return self.run(
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 271, in run
    result = self.process.run_blocking(
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 147, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 211, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 1:
Processing c:\users\anthon~1\appdata\local\temp\tmps299n1w3\jedi-0.18.1-py2.py3-none-any.whl
Installing collected packages: jedi
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\anthonyshaw\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\Local\\python\\mu\\mu_venv-38-20220716-165839\\Lib\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\auth\\management\\commands\\changepassword.pyi'

```

```default
2022-07-16 17:04:24,922 - mu.virtual_environment:857(create_venv) INFO: Created virtual environment using c:\Users\ANTHON~1\source\repos\mu\VENV~1\Scripts\python.exe at C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416
2022-07-16 17:04:24,922 - mu.virtual_environment:934(install_baseline_packages) INFO: Installing baseline packages.
2022-07-16 17:04:24,922 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['--version', '--disable-pip-version-check'] and envvars {}
2022-07-16 17:04:32,710 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:32,711 - mu.virtual_environment:274(run) DEBUG: Process output: pip 22.1.2 from C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\lib\site-packages\pip (python 3.8)
2022-07-16 17:04:32,711 - mu.virtual_environment:935(install_baseline_packages) INFO: pip version: pip 22.1.2 from C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\lib\site-packages\pip (python 3.8)
2022-07-16 17:04:32,713 - mu.virtual_environment:942(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\anthonyshaw\source\repos\mu\mu\wheels\1.1.1.zip
2022-07-16 17:04:33,549 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: asttokens-2.0.5-py2.py3-none-any.whl
2022-07-16 17:04:33,549 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\asttokens-2.0.5-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:04:40,954 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:40,954 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\asttokens-2.0.5-py2.py3-none-any.whl
Installing collected packages: asttokens
Successfully installed asttokens-2.0.5
2022-07-16 17:04:40,954 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: backcall-0.2.0-py2.py3-none-any.whl
2022-07-16 17:04:40,957 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\backcall-0.2.0-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:04:44,102 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:44,102 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\backcall-0.2.0-py2.py3-none-any.whl
Installing collected packages: backcall
Successfully installed backcall-0.2.0
2022-07-16 17:04:44,102 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: bitstring-3.1.9-py3-none-any.whl
2022-07-16 17:04:44,105 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\bitstring-3.1.9-py3-none-any.whl'] and envvars {}
2022-07-16 17:04:45,987 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:45,987 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\bitstring-3.1.9-py3-none-any.whl
Installing collected packages: bitstring
Successfully installed bitstring-3.1.9
2022-07-16 17:04:45,987 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: cffi-1.15.1-cp38-cp38-win_amd64.whl
2022-07-16 17:04:45,989 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\cffi-1.15.1-cp38-cp38-win_amd64.whl'] and envvars {}
2022-07-16 17:04:48,512 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:48,527 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\cffi-1.15.1-cp38-cp38-win_amd64.whl
Installing collected packages: cffi
Successfully installed cffi-1.15.1
2022-07-16 17:04:48,527 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: click-8.1.3-py3-none-any.whl
2022-07-16 17:04:48,529 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\click-8.1.3-py3-none-any.whl'] and envvars {}
2022-07-16 17:04:50,924 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:50,924 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\click-8.1.3-py3-none-any.whl
Installing collected packages: click
Successfully installed click-8.1.3
2022-07-16 17:04:50,924 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: colorama-0.4.5-py2.py3-none-any.whl
2022-07-16 17:04:50,926 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\colorama-0.4.5-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:04:52,774 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:52,791 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\colorama-0.4.5-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.4.5
2022-07-16 17:04:52,793 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: cryptography-37.0.4-cp36-abi3-win_amd64.whl
2022-07-16 17:04:52,793 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\cryptography-37.0.4-cp36-abi3-win_amd64.whl'] and envvars {}
2022-07-16 17:04:56,080 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:56,080 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\cryptography-37.0.4-cp36-abi3-win_amd64.whl
Installing collected packages: cryptography
Successfully installed cryptography-37.0.4
2022-07-16 17:04:56,084 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: decorator-5.1.1-py3-none-any.whl
2022-07-16 17:04:56,084 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\decorator-5.1.1-py3-none-any.whl'] and envvars {}
2022-07-16 17:04:57,897 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:04:57,898 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\decorator-5.1.1-py3-none-any.whl
Installing collected packages: decorator
Successfully installed decorator-5.1.1
2022-07-16 17:04:57,898 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: ecdsa-0.18.0-py2.py3-none-any.whl
2022-07-16 17:04:57,899 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\ecdsa-0.18.0-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:05:00,312 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:00,312 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\ecdsa-0.18.0-py2.py3-none-any.whl
Installing collected packages: ecdsa
Successfully installed ecdsa-0.18.0
2022-07-16 17:05:00,315 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: entrypoints-0.4-py3-none-any.whl
2022-07-16 17:05:00,316 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\entrypoints-0.4-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:02,075 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:02,091 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\entrypoints-0.4-py3-none-any.whl
Installing collected packages: entrypoints
Successfully installed entrypoints-0.4
2022-07-16 17:05:02,091 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: esptool-3.3.1-py3-none-any.whl
2022-07-16 17:05:02,094 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\esptool-3.3.1-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:04,962 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:04,962 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\esptool-3.3.1-py3-none-any.whl
Installing collected packages: esptool
Successfully installed esptool-3.3.1
2022-07-16 17:05:04,962 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: executing-0.8.3-py2.py3-none-any.whl
2022-07-16 17:05:04,967 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\executing-0.8.3-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:05:06,799 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:06,800 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\executing-0.8.3-py2.py3-none-any.whl
Installing collected packages: executing
Successfully installed executing-0.8.3
2022-07-16 17:05:06,801 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: Flask-2.0.3-py3-none-any.whl
2022-07-16 17:05:06,802 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\Flask-2.0.3-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:09,255 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:09,255 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\flask-2.0.3-py3-none-any.whl
Installing collected packages: Flask
Successfully installed Flask-2.0.3
2022-07-16 17:05:09,257 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: ipykernel-5.5.6-py3-none-any.whl
2022-07-16 17:05:09,257 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\ipykernel-5.5.6-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:12,323 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:12,323 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\ipykernel-5.5.6-py3-none-any.whl
Installing collected packages: ipykernel
Successfully installed ipykernel-5.5.6
2022-07-16 17:05:12,323 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: ipython-8.4.0-py3-none-any.whl
2022-07-16 17:05:12,339 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\ipython-8.4.0-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:20,075 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:20,075 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\ipython-8.4.0-py3-none-any.whl
Installing collected packages: ipython
Successfully installed ipython-8.4.0
2022-07-16 17:05:20,075 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: ipython_genutils-0.2.0-py2.py3-none-any.whl
2022-07-16 17:05:20,088 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\ipython_genutils-0.2.0-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:05:22,219 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:22,219 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\ipython_genutils-0.2.0-py2.py3-none-any.whl
Installing collected packages: ipython-genutils
Successfully installed ipython-genutils-0.2.0
2022-07-16 17:05:22,224 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: itsdangerous-2.1.2-py3-none-any.whl
2022-07-16 17:05:22,224 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\itsdangerous-2.1.2-py3-none-any.whl'] and envvars {}
2022-07-16 17:05:24,111 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-07-16 17:05:24,111 - mu.virtual_environment:274(run) DEBUG: Process output: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\itsdangerous-2.1.2-py3-none-any.whl
Installing collected packages: itsdangerous
Successfully installed itsdangerous-2.1.2
2022-07-16 17:05:24,113 - mu.virtual_environment:916(install_from_zipped_wheels) INFO: About to install from wheel: jedi-0.18.1-py2.py3-none-any.whl
2022-07-16 17:05:24,113 - mu.virtual_environment:139(run_blocking) INFO: About to run blocking C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\ANTHON~1\\AppData\\Local\\Temp\\tmp1i7ucdp5\\jedi-0.18.1-py2.py3-none-any.whl'] and envvars {}
2022-07-16 17:05:26,295 - mu.virtual_environment:189(wait) DEBUG: Finished: True; exitStatus 0; exitCode 1
2022-07-16 17:05:26,295 - mu.virtual_environment:210(wait) ERROR: Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\jedi-0.18.1-py2.py3-none-any.whl
Installing collected packages: jedi
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\anthonyshaw\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\Local\\python\\mu\\mu_venv-38-20220716-170416\\Lib\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\auth\\management\\commands\\changepassword.pyi'
2022-07-16 17:05:26,368 - mu.virtual_environment:677(ensure_and_create) ERROR: Process finished but with error code 1:
Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\jedi-0.18.1-py2.py3-none-any.whl
Installing collected packages: jedi
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\anthonyshaw\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\Local\\python\\mu\\mu_venv-38-20220716-170416\\Lib\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\auth\\management\\commands\\changepassword.pyi'
2022-07-16 17:05:26,382 - mu.virtual_environment:574(quarantine_venv) INFO: Quarantined C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416 as C:\Users\anthonyshaw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\python\mu\mu_venv-38-20220716-170416.FAILED
Traceback (most recent call last):
  File "C:\Users\anthonyshaw\source\repos\mu\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\anthonyshaw\source\repos\mu\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 828, in create
    self.install_baseline_packages()
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 947, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 921, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 295, in install
    return self.run(
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 271, in run
    result = self.process.run_blocking(
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 147, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\anthonyshaw\source\repos\mu\mu\virtual_environment.py", line 211, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 1:
Processing c:\users\anthon~1\appdata\local\temp\tmp1i7ucdp5\jedi-0.18.1-py2.py3-none-any.whl
Installing collected packages: jedi
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\anthonyshaw\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\Local\\python\\mu\\mu_venv-38-20220716-170416\\Lib\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\auth\\management\\commands\\changepassword.pyi'
```

I checked the path, that `.pyi` doesn't exist, but much of the other source files are there.

**Comment by tonybaloney** [comment]
Related to #228
