### ISSUE TITLE
Crash Report - installing on Anaconda

### ISSUE THREAD

**Issue by Ambercam** [mu-editor/crash-reports#233]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_GB
Platform: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

```
Traceback (most recent call last):
  File "/Users/simonjackson/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/Users/simonjackson/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/Users/simonjackson/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/Users/simonjackson/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
[mu.log](https://github.com/mu-editor/crash-reports/files/9165857/mu.log)

  File "/Users/simonjackson/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /Users/simonjackson/opt/anaconda3/bin/python3 at /Users/simonjackson/Library/Application Support/mu/mu_venv-38-20220722-085402
STDERR: /Users/simonjackson/opt/anaconda3/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @Ambercam,

I don't have any experience using Anaconda, could you run these two commands, and paste the results here, on the same Python environment used to install Mu? It'll let us know if the issue is the same as:
- https://github.com/mu-editor/mu/issues/1954

```
python -m pip list --verbose
```

```
python -I -m pip list --verbose
```
