### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Multilingual-Coder** [mu-editor/crash-reports#24]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.13.0-28-generic mu-editor/mu#31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/noah/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/noah/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/noah/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/noah/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/noah/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/noah/.local/share/mu/mu_venv-38-20220215-225908
STDERR: /usr/bin/python3: No module named virtualenv

```
[mu.log](https://github.com/mu-editor/mu/files/8076640/mu.log)

**Comment by carlosperate** [comment]
Hi @Multilingual-Coder 
Were you able to resolve with issue with Mu with the steps listed in my last message?

**Comment by carlosperate** [comment]
Awesome, thanks for the update and for all the testingh!
