### ISSUE TITLE
Windows 10 Failed Install: ImportError: bad magic number in 'tornado'

### ISSUE THREAD

**Issue by bkofford** [mu-editor/crash-reports#251]
Redownloading uninstalling and re-installing did not correct the issue.
I have also tried turning off Sophos endpoint security features with no change.

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
t)
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 774, in create
    self.install_jupyter_kernel()
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 830, in install_jupyter_kernel
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to install kernel
STDERR: Traceback (most recent call last):
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\ipykernel\__main__.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\brian.kofford\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\ipykernel\kernelapp.py", line 14, in <module>
    import tornado
ImportError: bad magic number in 'tornado': b'\xd1\xf2\r\n'

```

**Comment by bkofford** [comment]
The log imported into the code block, so the link didn't happen. Here: 

[mu.log](https://github.com/mu-editor/crash-reports/files/9383122/mu.log)

**Comment by bkofford** [comment]
I found and uninstalled a version of Python I didn't realize I had. This did not correct the issue.

**Comment by carlosperate** [comment]
Thanks for the report and the log @bkofford!

I think this issue might have been fixed in https://github.com/mu-editor/mu/pull/2237, but it hasn't been released yet. Would you be able to try one of the latest test installers to check if that works for you?

It'd help if you could uninstall the previous version of Mu before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">

**Comment by bkofford** [comment]
That did the trick. Thank you!

**Comment by carlosperate** [comment]
Awesome, thanks for testing the installer, glad it works now 🎉
