### ISSUE TITLE
Not allowing me to load in to the Editor

### ISSUE THREAD

**Issue by Zdzblo** [mu-editor/crash-reports#280]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.3
Locale: en_PH
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 551, in ensure_key_modules
    subprocess.run(
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Luis Cinconiegue\\AppData\\Local\\python\\mu\\mu_venv-38-20220913-114055\\scripts\\python.exe', '-c', 'import pgzero']' returned non-zero exit status 101.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 442, in ensure_and_create
    self.ensure()
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 471, in ensure
    self.ensure_key_modules()
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 560, in ensure_key_modules
    raise VirtualEnvironmentError(message)
mu.virtual_environment.VirtualEnvironmentError: Failed to import: pgzero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 300, in installed
    next(iterlines)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 162, in run
    raise ex
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 449, in ensure_and_create
    self.create()
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 598, in create
    self.register_baseline_packages()
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 665, in register_baseline_packages
    packages = list(self.pip.installed())
  File "C:\Users\Luis Cinconiegue\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 305, in installed
    raise VirtualEnvironmentError("Unable to parse installed packages")
mu.virtual_environment.VirtualEnvironmentError: Unable to parse installed packages

```

**Comment by carlosperate** [comment]
Hi @Zdzblo, thanks for the report.

It looks like you are running a very old version of Mu. Could you try downloading the latest version from https://codewith.mu and trying again?

**Comment by carlosperate** [comment]
Thanks for the report @Zdzblo  ! 

The new Mu Editor v1.2.0 release yesterday fixes this issue, if you install the latest version for your operating system from the Mu website it should now work: https://codewith.mu/en/download

I'll close this crash report as fixed, but if you encounter this or any other crash with v1.2.0 please open a new crash report and we'll be happy to look into that issue 👍

Thanks again!
