### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cwsmith4** [mu-editor/crash-reports#282]
Version: 1.1.1
Locale: en_US
Platform: Linux 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/pi/.local/share/mu/mu_venv-37-20220915-192031
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @cwsmith4, thanks for the report!

There has been a few fixes recently that have not been release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">
