### ISSUE TITLE
Crash Report: attempted to start CMD.EXE from installer location

### ISSUE THREAD

**Issue by davidhbrown-uri** [mu-editor/crash-reports#284]
The referenced UNC path was where I put the installer. I'm not sure why the installed program is attempting to reference the installer's path. Even if it weren't a UNC path, there are reasons it might not be available such as having been on a removable (flash) drive, or having been deleted because the installer is no longer needed.

[mu.log](https://github.com/mu-editor/crash-reports/files/9587501/mu.log)

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
Traceback (most recent call last):
  File "C:\Users\dave\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\dave\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\dave\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 627, in ensure_and_create
    self.ensure()
  File "C:\Users\dave\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 665, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\dave\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 732, in ensure_interpreter_version
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Mu interpreter at version 38; venv interpreter at version 38


STDERR: '\\DISKSTATION\software\Drivers and Manuals\Adafruit\QT-Py'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory..

```

**Comment by carlosperate** [comment]
Thanks for the report @davidhbrown-uri, that's an interestiing error.

Basically the problem is that Mu runs `import sys; print("%s%s" % sys.version_info[:2])` expecting it to print `38` to stdout and nothing to stderr, and the shell ends up adding  the`'\\DISKSTATION\... CMD.EXE was started with...` message to stderr.

I think we can problably patch Mu to ignore anything after the "38" part of the string for this specific check, but it would be really useful to understand why the error message is triggered as well, as it might affect other commands Mu tries to run.

Did this happen as soon as Mu was installed? When the installer launches Mu? Maybe that explains why the current working directory is the installer location?

Does the same error appears when launching Mu from the start menu shortcut?

**Comment by davidhbrown-uri** [comment]
I had uninstalled an older version of Mu, then installed this one and it failed to launch from the installer. So this was a second launch (from the start menu shortcut) but the first to display anything. Just tried again from the start menu with no error (except that I don't have a device plugged in at the moment).  Definitely not a major issue for me as it seems to have gone away, but the (very nicely formatted) browser window that appeared seemed to suggest you really wanted to know :-)
