### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by amnush** [mu-editor/crash-reports#304]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: fr_FR
Platform: Windows 10 10.0.22000 AMD64

```
\\AppData\\Local\\python\\mu\\mu_venv-38-20221008-181142\\Lib\\site-packages'
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\LENOVO\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
    self._uninstall_previous_version()
  File "C:\Users\LENOVO\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 154, in _uninstall_previous_version
    existing_dist = next(paths, None)
  File "C:\Users\LENOVO\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 153, in <genexpr>
    paths = (p for p in in_folders if p.stem.split("-")[0] == dist_name and p.suffix == ".dist-info" and p.is_dir())
  File "C:\Users\LENOVO\AppData\Local\Programs\Mu Editor\Python\lib\pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] Le chemin dï¿½accï¿½s spï¿½cifiï¿½ est introuvable: 'C:\\Users\\LENOVO\\AppData\\Local\\python\\mu\\mu_venv-38-20221008-181142\\Lib\\site-packages'

```

**Comment by amnush** [comment]
i want mu to start working
