### ISSUE TITLE
Mu crashes whenever trying to view files on devices / run code. Worked fine two days ago.  (wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted)

### ISSUE THREAD

**Issue by oorischubert** [mu-editor/crash-reports#308]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 760, in on_ls_fail
    self.disable()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted


LOGFILE:

Starting Mu 1.1.1
2022-10-11 01:17:56,538 - root:270(run) INFO: uname_result(system='Darwin', node='vl965-172-31-112-104.wireless.umass.edu', release='21.6.0', version='Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64', machine='x86_64', processor='i386')
2022-10-11 01:17:56,559 - root:271(run) INFO: Platform: macOS-10.16-x86_64-i386-64bit
2022-10-11 01:17:56,560 - root:272(run) INFO: Python path: ['/', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python38.zip', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/lib-dynload', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/setuptools-57.4.0-py3.8.egg', '/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/pip-21.1.3-py3.8.egg']
2022-10-11 01:17:56,560 - root:273(run) INFO: Language code: en_US
2022-10-11 01:17:56,562 - mu.settings:220(load) WARNING: No settings file found at /Users/oorischubert/Library/Application Support/mu/settings.json; skipping
2022-10-11 01:17:56,839 - mu.virtual_environment:585(ensure_and_create) INFO: Added log handler.
2022-10-11 01:17:56,840 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2022-10-11 01:17:56,841 - mu.virtual_environment:685(ensure_path) INFO: Virtual Environment found at: /Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819
2022-10-11 01:17:56,842 - mu.virtual_environment:698(ensure_interpreter) INFO: Interpreter found at: /Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python
2022-10-11 01:17:56,842 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import sys; print("%s%s" % sys.version_info[:2])') with kwargs {'shell': False}
2022-10-11 01:17:56,944 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 38
2022-10-11 01:17:56,950 - mu.virtual_environment:730(ensure_interpreter_version) INFO: Both interpreters at version 38
2022-10-11 01:17:56,964 - mu.virtual_environment:759(ensure_pip) INFO: Pip found at: /Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/pip
2022-10-11 01:17:56,964 - mu.virtual_environment:742(ensure_key_modules) DEBUG: Verifying import of: pgzero
2022-10-11 01:17:56,964 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import pgzero') with kwargs {'shell': False}
2022-10-11 01:17:57,009 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-10-11 01:17:57,010 - mu.virtual_environment:742(ensure_key_modules) DEBUG: Verifying import of: flask
2022-10-11 01:17:57,010 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import flask') with kwargs {'shell': False}
2022-10-11 01:17:57,323 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-10-11 01:17:57,323 - mu.virtual_environment:742(ensure_key_modules) DEBUG: Verifying import of: ipykernel
2022-10-11 01:17:57,323 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import ipykernel') with kwargs {'shell': False}
2022-10-11 01:17:58,181 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-10-11 01:17:58,181 - mu.virtual_environment:742(ensure_key_modules) DEBUG: Verifying import of: ipython_genutils
2022-10-11 01:17:58,181 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import ipython_genutils') with kwargs {'shell': False}
2022-10-11 01:17:58,222 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-10-11 01:17:58,223 - mu.virtual_environment:742(ensure_key_modules) DEBUG: Verifying import of: esptool
2022-10-11 01:17:58,223 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819/bin/python', '-c', 'import esptool') with kwargs {'shell': False}
2022-10-11 01:17:58,297 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-10-11 01:17:58,297 - mu.virtual_environment:628(ensure_and_create) INFO: Valid virtual environment found at /Users/oorischubert/Library/Application Support/mu/mu_venv-38-20220912-000819
2022-10-11 01:17:58,297 - mu.settings:169(save) DEBUG: Saving to /Users/oorischubert/Library/Application Support/mu/venv.json
2022-10-11 01:17:58,323 - mu.logic:768(__init__) INFO: Setting up editor.
2022-10-11 01:17:58,324 - mu.logic:789(__init__) INFO: Log directory: /Users/oorischubert/Library/Logs/mu
2022-10-11 01:17:58,324 - mu.logic:790(__init__) INFO: Data directory: /Users/oorischubert/Library/Application Support/mu
2022-10-11 01:17:58,324 - mu.logic:804(setup) INFO: Available modes: python, circuitpython, microbit, esp, web, pyboard, debugger, pygamezero, lego, pico
2022-10-11 01:17:58,324 - mu.modes.base:61(get_default_workspace) INFO: Using workspace /Users/oorischubert/mu_code from settings file
2022-10-11 01:17:58,374 - mu.modes.base:61(get_default_workspace) INFO: Using workspace /Users/oorischubert/mu_code from settings file
2022-10-11 01:17:58,375 - mu.logic:1549(change_mode) INFO: Workspace directory: /Users/oorischubert/mu_code
2022-10-11 01:17:58,375 - mu.logic:878(restore_session) DEBUG: <SessionSettings from /Users/oorischubert/Library/Application Support/mu/session.json>
2022-10-11 01:17:58,380 - mu.logic:900(restore_session) INFO: Loaded files.
2022-10-11 01:17:58,381 - mu.logic:906(restore_session) INFO: User defined environment variables: {}
2022-10-11 01:17:58,381 - mu.logic:911(restore_session) INFO: Minify scripts on micro:bit? False
2022-10-11 01:17:58,397 - mu.modes.base:61(get_default_workspace) INFO: Using workspace /Users/oorischubert/mu_code from settings file
2022-10-11 01:17:58,397 - mu.logic:1549(change_mode) INFO: Workspace directory: /Users/oorischubert/mu_code
2022-10-11 01:17:58,488 - mu.logic:962(restore_session) INFO: Starting with blank file.
2022-10-11 01:17:59,362 - mu.interface.main:1061(show_confirmation) DEBUG: Detected new CP210x device.
2022-10-11 01:17:59,363 - mu.interface.main:1062(show_confirmation) DEBUG: Would you like to change Mu to the ESP MicroPython mode?
2022-10-11 01:18:01,018 - mu.modes.base:61(get_default_workspace) INFO: Using workspace /Users/oorischubert/mu_code from settings file
2022-10-11 01:18:01,018 - mu.logic:1549(change_mode) INFO: Workspace directory: /Users/oorischubert/mu_code
2022-10-11 01:18:01,019 - mu.logic:747(check_usb) INFO: esp device connected on port: /dev/cu.usbserial-0001(VID: 0x10C4, PID: 0xEA60, manufacturer: 'Silicon Labs')
2022-10-11 01:18:09,434 - mu.modes.esp:175(run) INFO: Running script.
2022-10-11 01:18:09,435 - mu.modes.base:112(open) INFO: Connecting to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:09,529 - mu.modes.base:130(open) INFO: Connected to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:09,536 - mu.modes.base:503(add_repl) INFO: Started REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:09,536 - mu.modes.base:474(toggle_repl) INFO: Toggle REPL on.
2022-10-11 01:18:09,536 - mu.modes.base:188(send_commands) INFO: [b'\x03', b'\x03', b'\x01', b'\x04', b'\x03', b'\x03', b'print("\\n");', b'# Write your code here :-)\r', b'print("hello World")\r', b'\r', b'\x04', b'\x02']
2022-10-11 01:18:09,537 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:09,550 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:09,556 - mu.modes.base:162(execute) INFO: Sending command b'\x01'
2022-10-11 01:18:09,559 - mu.modes.base:162(execute) INFO: Sending command b'\x04'
2022-10-11 01:18:09,561 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:09,564 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:09,566 - mu.modes.base:162(execute) INFO: Sending command b'print("\\n");'
2022-10-11 01:18:09,569 - mu.modes.base:162(execute) INFO: Sending command b'# Write your code here :-)\r'
2022-10-11 01:18:09,572 - mu.modes.base:162(execute) INFO: Sending command b'print("hello World")\r'
2022-10-11 01:18:09,574 - mu.modes.base:162(execute) INFO: Sending command b'\r'
2022-10-11 01:18:09,577 - mu.modes.base:162(execute) INFO: Sending command b'\x04'
2022-10-11 01:18:09,579 - mu.modes.base:162(execute) INFO: Sending command b'\x02'
2022-10-11 01:18:15,510 - mu.modes.esp:175(run) INFO: Running script.
2022-10-11 01:18:15,511 - mu.modes.base:188(send_commands) INFO: [b'\x03', b'\x03', b'\x01', b'\x04', b'\x03', b'\x03', b'print("\\n");', b'# Write your code here :-)\r', b'print("hello World")\r', b'\r', b'\x04', b'\x02']
2022-10-11 01:18:15,511 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:15,514 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:15,516 - mu.modes.base:162(execute) INFO: Sending command b'\x01'
2022-10-11 01:18:15,519 - mu.modes.base:162(execute) INFO: Sending command b'\x04'
2022-10-11 01:18:15,522 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:15,524 - mu.modes.base:162(execute) INFO: Sending command b'\x03'
2022-10-11 01:18:15,527 - mu.modes.base:162(execute) INFO: Sending command b'print("\\n");'
2022-10-11 01:18:15,530 - mu.modes.base:162(execute) INFO: Sending command b'# Write your code here :-)\r'
2022-10-11 01:18:15,532 - mu.modes.base:162(execute) INFO: Sending command b'print("hello World")\r'
2022-10-11 01:18:15,535 - mu.modes.base:162(execute) INFO: Sending command b'\r'
2022-10-11 01:18:15,538 - mu.modes.base:162(execute) INFO: Sending command b'\x04'
2022-10-11 01:18:15,540 - mu.modes.base:162(execute) INFO: Sending command b'\x02'
2022-10-11 01:18:16,769 - mu.modes.base:136(close) INFO: Closing connection to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:16,891 - mu.modes.base:471(toggle_repl) INFO: Toggle REPL off.
2022-10-11 01:18:17,915 - mu.modes.base:112(open) INFO: Connecting to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:18,005 - mu.modes.base:130(open) INFO: Connected to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:18,013 - mu.modes.base:503(add_repl) INFO: Started REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:18,013 - mu.modes.base:474(toggle_repl) INFO: Toggle REPL on.
2022-10-11 01:18:23,301 - mu.modes.base:136(close) INFO: Closing connection to REPL on port: /dev/cu.usbserial-0001
2022-10-11 01:18:23,425 - mu.modes.base:471(toggle_repl) INFO: Toggle REPL off.
2022-10-11 01:18:23,886 - mu.modes.base:61(get_default_workspace) INFO: Using workspace /Users/oorischubert/mu_code from settings file
2022-10-11 01:18:23,898 - mu.modes.esp:214(toggle_files) INFO: Toggle filesystem on.
2022-10-11 01:18:26,344 - mu.modes.base:686(ls) ERROR: Could not enter raw REPL.
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/modes/base.py", line 683, in ls
    result = tuple(microfs.ls(self.serial))
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 185, in ls
    out, err = execute(["import os", "print(os.listdir())"], serial)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 139, in execute
    raw_on(serial)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 91, in raw_on
    flush_to_msg(serial, raw_repl_msg)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 72, in flush_to_msg
    raise IOError("Could not enter raw REPL.")
OSError: Could not enter raw REPL.
2022-10-11 01:18:26,358 - mu.interface.main:1033(show_message) DEBUG: There was a problem getting the list of files on the device. Please check Mu's logs for technical information. Alternatively, try unplugging/plugging-in your device and/or restarting Mu.
2022-10-11 01:18:26,358 - mu.interface.main:1034(show_message) DEBUG: None
2022-10-11 01:18:30,180 - mu.interface.main:1033(show_message) DEBUG: Could not find an attached ESP8266/ESP32
2022-10-11 01:18:30,181 - mu.interface.main:1034(show_message) DEBUG: Please make sure the device is plugged into this computer.

The device must have MicroPython flashed onto it before the file system will work.

Finally, press the device's reset button and wait a few seconds before trying again.
2022-10-11 01:18:31,345 - mu.logic:730(check_usb) INFO: esp device disconnected on port: /dev/cu.usbserial-0001(VID: 0x10C4, PID: 0xEA60, manufacturer Silicon Labs)
2022-10-11 01:18:31,794 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 760, in on_ls_fail
    self.disable()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/interface/panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted
2022-10-11 01:18:31,935 - mu.settings:169(save) DEBUG: Saving to /Users/oorischubert/Library/Application Support/mu/session.json
2022-10-11 01:18:31,938 - mu.settings:169(save) DEBUG: Saving to /Users/oorischubert/Library/Application Support/mu/venv.json
2022-10-11 01:20:36,802 - root:269(run) INFO: 


```

**Comment by carlosperate** [comment]
Hi @oorischubert, thanks for the report!

There has been a few fixes recently that have not been release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/2697356255

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/4189262/182040197-23964238-e5e0-4ffb-a441-6ed1150d48e0.png">

**Comment by oorischubert** [comment]
This seems to have worked. Though every once in a while it still cannot find the device, it does not crash like before. Repressing the files button a couple times eventually solves it. I do not have these issues with the regular pico, could this problem be with the pico w's specific version of MicroPython?

<img width="927" alt="Screen Shot 2022-10-11 at 4 42 35 PM" src="https://user-images.githubusercontent.com/61707814/195194636-2b259d20-8e70-45f0-9c10-2845b4f0b018.png">

**Comment by carlosperate** [comment]
Thanks for the report @oorischubert!

The new Mu Editor v1.2.0 released now includes this fix and can be downloaded from: https://codewith.mu/en/download

I'll close this crash report as fixed, if you'd like to report the other issue in the main Mu repository we can look at it over there 👍

Thanks again!
