### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Cl1432** [mu-editor/crash-reports#335]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.22000 AMD64

```
thon\mu\mu_venv-38-20221102-164417
RuntimeError: failed to build image pip because:
Traceback (most recent call last):
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 39, in install
    self._sync(filename, into)
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
    copy(src, dst)
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 52, in copy
    method(norm(src), norm(dest))
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 59, in copytree
    os.makedirs(dest_dir)
  File "C:\Users\Cllee\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Cllee\\AppData\\Local\\python\\mu\\mu_venv-38-20221102-164417\\Lib\\site-packages\\pip\\_vendor\\pygments\\styles'

```

**Comment by carlosperate** [comment]
Thanks for the report @Cl1432!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\Cllee\AppData\Local\python\mu\Logs\mu.log`

**Comment by Cl1432** [comment]
Sorry for late reply. This issue has been resolved, but thank you for reaching out.
