### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by patterson192** [mu-editor/crash-reports#337]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
Traceback (most recent call last):
  File "C:\Users\brpbr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 165, in <lambda>
    remaining_task = lambda commands=remainder: self.execute(commands)
  File "C:\Users\brpbr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 163, in execute
    self.write(command)
  File "C:\Users\brpbr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 149, in write
    self.serial.write(data)
AttributeError: 'NoneType' object has no attribute 'write'

```

**Comment by carlosperate** [comment]
Hi @patterson192, thanks for the report!

There has been a few fixes recently that have not been release yet. Would you be able to try the latest test installer to check if that works for you?

It'd help if you could **uninstall the previous version of Mu** before installing this one, as it will be listed as also being v1.1.1.

To download it go to this link while logged into GitHub (otherwise the download link doesn't appear), and download the `mu-editor-Windows-...` file from the bottom of the page: https://github.com/mu-editor/mu/actions/runs/3235316433

<img width="1092" alt="Screenshot 2022-10-21 at 13 13 28" src="https://user-images.githubusercontent.com/4189262/197193169-427a2669-44e3-4b4b-8b6e-3e5431d3724c.png">

**Comment by patterson192** [comment]
Sure. I'll try that as soon as possible
