### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by boc99** [mu-editor/crash-reports#347]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: it_IT
Platform: Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/boc/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/boc/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/boc/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/boc/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/boc/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/boc/.local/share/mu/mu_venv-38-20221107-082901
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by boc99** [comment]
Linux mint 20 phython 3.8
