### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by sreekalapola** [mu-editor/crash-reports#357]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_IN
Platform: Windows 10 10.0.19044 AMD64

```
nv-38-20221116-111730
RuntimeError: failed to build image setuptools because:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 55, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
    self._sync(filename, into)
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 11, in _sync
    copy(src, dst)
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 33, in copy
    ensure_safe_to_do(src, dest)
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 23, in ensure_safe_to_do
    dest.unlink()
  File "C:\Users\HP\AppData\Local\Programs\MUEDIT~1\Python\lib\pathlib.py", line 1325, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\HP\\AppData\\Local\\python\\mu\\mu_venv-38-20221116-111730\\Lib\\site-packages\\distutils-precedence.pth'

```

**Comment by carlosperate** [comment]
Thanks for the report @sreekalapola!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\HP\AppData\Local\Programs\MUEDIT~1\AppData\Local\python\mu\Logs\mu.log`
