### ISSUE TITLE
Error upon Mu Editor startup after macOS installation

### ISSUE THREAD

**Issue by seasonedgeek** [mu-editor/crash-reports#360]
At step 5, I started the Mu Editor, per instruction found on the [How to install Mu on macOS with the Official Installer](https://codewith.mu/en/howto/1.2/install_macos) page. I'm running macOS Catalina 10.15.7 (19H2026)).

The initial Mu Editor startup resulted in the display of this `traceback` message:

```sh
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 160, in run
    raise ex
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 701, in ensure
    self.ensure_key_modules()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 806, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pgzero'
```

Please see my [mu.log](https://github.com/mu-editor/crash-reports/files/10045388/mu.log) for details. Also the `pgzero` package seems to be missing in the `/Applications/Mu\ Editor.app/Contents/Resources/Python/lib/python3.8/site-packages` directory. See [mu-editor_python3.8_site-packages.txt](https://github.com/mu-editor/crash-reports/files/10045445/mu-editor_python3.8_site-packages.txt).

**Comment by seasonedgeek** [comment]
Also, the contents of the `~/Library/Application\ Support/virtualenv/py_info/1/mu.json` file may be helpful for debugging...

```json
{
  "content": {
    "_creators": null,
    "architecture": 64,
    "base_exec_prefix": "/Applications/Mu Editor.app/Contents/Resources/Python",
    "base_prefix": "/Applications/Mu Editor.app/Contents/Resources/Python",
    "distutils_install": {
      "data": "",
      "headers": "include/python3.8/UNKNOWN",
      "platlib": "lib/python3.8/site-packages",
      "purelib": "lib/python3.8/site-packages",
      "scripts": "bin"
    },
    "exec_prefix": "/Applications/Mu Editor.app/Contents/Resources/Python",
    "executable": "/Applications/Mu Editor.app/Contents/Resources/Python/bin/Mu Editor",
    "file_system_encoding": "utf-8",
    "has_venv": true,
    "implementation": "CPython",
    "max_size": 9223372036854775807,
    "original_executable": "/Applications/Mu Editor.app/Contents/Resources/Python/bin/Mu Editor",
    "os": "posix",
    "path": [
      "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/discovery",
      "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python38.zip",
      "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8",
      "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/lib-dynload",
      "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages"
    ],
    "platform": "darwin",
    "prefix": "/Applications/Mu Editor.app/Contents/Resources/Python",
    "real_prefix": null,
    "stdout_encoding": "utf-8",
    "sysconfig": {
      "makefile_filename": "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/config-3.8-darwin/Makefile"
    },
    "sysconfig_paths": {
      "data": "{base}",
      "include": "{installed_base}/include/python{py_version_short}{abiflags}",
      "platlib": "{platbase}/lib/python{py_version_short}/site-packages",
      "platstdlib": "{platbase}/lib/python{py_version_short}",
      "purelib": "{base}/lib/python{py_version_short}/site-packages",
      "scripts": "{base}/bin",
      "stdlib": "{installed_base}/lib/python{py_version_short}"
    },
    "sysconfig_scheme": null,
    "sysconfig_vars": {
      "PYTHONFRAMEWORK": "",
      "abiflags": "",
      "base": "/Applications/Mu Editor.app/Contents/Resources/Python",
      "installed_base": "/Applications/Mu Editor.app/Contents/Resources/Python",
      "platbase": "/Applications/Mu Editor.app/Contents/Resources/Python",
      "py_version_short": "3.8"
    },
    "system_executable": "/Applications/Mu Editor.app/Contents/Resources/Python/bin/Mu Editor",
    "system_stdlib": "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8",
    "system_stdlib_platform": "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8",
    "version": "3.8.12 (default, Oct 18 2021, 00:42:52) \n[Clang 13.0.0 ]",
    "version_info": {
      "major": 3,
      "micro": 12,
      "minor": 8,
      "releaselevel": "final",
      "serial": 0
    },
    "version_nodot": "38"
  },
  "path": "/Applications/Mu Editor.app/Contents/Resources/Python/bin/Mu Editor",
  "st_mtime": 1668429922.0
}
```
