### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lee2sman** [mu-editor/crash-reports#39]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Linux 5.4.0-105-generic mu-editor/mu#119~18.04.1-Ubuntu SMP Tue Mar 8 11:21:24 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/lee/.local/lib/python3.6/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/lee/.local/lib/python3.6/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/lee/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/lee/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lee/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lee/.local/share/mu/mu_venv-36-20220327-230942
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @lee2sman 
Were you able to resolve with issue with Mu with the steps listed in my last message?

**Comment by lee2sman** [comment]
Hi @carlosperate I'm giving up on Mu for now as I'm not working on this project anymore. Feel free to close the issue.

**Comment by carlosperate** [comment]
Okay, thanks for the update.
If you want to give it a go in the future we've recently release a Linux AppImage, which should work out of the box: https://codewith.mu/en/download
