### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dblanding** [mu-editor/crash-reports#394]
[mu.log](https://github.com/mu-editor/crash-reports/files/10367537/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Linux 5.15.0-57-generic #63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/doug/.local/lib/python3.8/site-packages/mu/app.py", line 160, in run
    raise ex
  File "/home/doug/.local/lib/python3.8/site-packages/mu/app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "/home/doug/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "/home/doug/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 827, in create
    self.create_venv()
  File "/home/doug/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/doug/.local/share/mu/mu_venv-38-20230107-204241
STDERR: /usr/bin/python3: No module named virtualenv

```
[mu.log](https://github.com/mu-editor/crash-reports/files/10367539/mu.log)

**Comment by dblanding** [comment]
I installed mu-editor using `pip3 install mu-editor` and then `sudo apt install mu-editor`.
It was working perfectly. Then I installed shortcut, and restarted my computer and now it won't launch.
