### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by GeorgiaJoyce** [mu-editor/crash-reports#397]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_CA
Platform: Windows 10 10.0.22621 AMD64

C:\Users\georg\AppData\Local\python\mu\Logs\mu.log
```
Traceback (most recent call last):
  File "C:\Users\georg\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\georg\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\georg\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "C:\Users\georg\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 827, in create
    self.create_venv()
  File "C:\Users\georg\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\georg\AppData\Local\Programs\MUEDIT~1\Python\pythonw.exe at C:\Users\georg\AppData\Local\python\mu\mu_venv-38-20230109-135617
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\georg\\AppData\\Local\\python\\mu\\mu_venv-38-20230109-135617\\Lib\\site-packages'

```

**Comment by carlosperate** [comment]
Hi @GeorgiaJoyce, thanks for the report !

Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\georg\AppData\Local\python\mu\Logs\mu.log`
You should be able to drag & drop it into a comment in this page.

Based on the error I think maybe there were 2 instances of Mu running in parallel and racing each other at creating these directories, which would be this issue: https://github.com/mu-editor/mu/issues/1755

If you try to run Mu again, and ensure it is only running once, do you still get this problem?
