### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ivanramos92** [mu-editor/crash-reports#401]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 376, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 836, in setup
    os.makedirs(fonts_path)
  File "C:\Users\ivanr\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\ivanr\\mu_code\\fonts'

```

2023-01-15 00:01:00,217 - mu.modes.base:61(get_default_workspace) INFO: Using workspace C:\Users\ivanr\mu_code from settings file
2023-01-15 00:01:00,220 - mu.logic:1583(change_mode) INFO: Workspace directory: C:\Users\ivanr\mu_code
2023-01-15 00:01:00,221 - mu.logic:890(restore_session) DEBUG: <SessionSettings from C:\Users\ivanr\AppData\Local\python\mu\session.json>
2023-01-15 00:01:00,241 - mu.logic:1530(select_mode) INFO: Showing available modes: ['python', 'snek', 'circuitpython', 'microbit', 'esp', 'web', 'pyboard', 'debugger', 'pygamezero', 'lego', 'pico']

**Comment by carlosperate** [comment]
Hi @ivanramos92, thanks for the report !

Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\ivanr\AppData\Local\python\mu\Logs\mu.log`
You should be able to drag & drop it into a comment in this page.

Based on the error I think maybe there were 2 instances of Mu running in parallel and racing each other at creating these directories, which would be this issue: https://github.com/mu-editor/mu/issues/1755

If you try to run Mu again, and ensure it is only running once, do you still get this problem?
