### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by 8095519532** [mu-editor/crash-reports#413]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_IN
Platform: Windows 10 10.0.22000 AMD64

```
env.ensure_and_create(self.display_text)
  File "C:\Users\HP\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Users\HP\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 701, in ensure
    self.ensure_key_modules()
  File "C:\Users\HP\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 806, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\HP\AppData\Local\python\mu\mu_venv-38-20230125-124456\lib\site-packages\flask\__init__.py", line 3, in <module>
    from werkzeug.exceptions import abort as abort
  File "C:\Users\HP\AppData\Local\python\mu\mu_venv-38-20230125-124456\lib\site-packages\werkzeug\__init__.py", line 1, in <module>
    from .serving import run_simple as run_simple
  File "C:\Users\HP\AppData\Local\python\mu\mu_venv-38-20230125-124456\lib\site-packages\werkzeug\serving.py", line 18, in <module>
    import socketserver
  File "C:\Users\HP\Downloads\socketserver.py", line 2, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'

```

**Comment by 8095519532** [comment]
there is crash error in mueditor
