### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Polderrider** [mu-editor/crash-reports#415]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_AU
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Mmm...M&Ms\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\Mmm...M&Ms\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Mmm...M&Ms\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Users\Mmm...M&Ms\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 699, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\Mmm...M&Ms\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 779, in ensure_interpreter_version
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to run venv interpreter C:\Users\Mmm...M&Ms\AppData\Local\python\mu\mu_venv-38-20230127-082825\scripts\python.exe
STDERR: 'C:\Users\Mmm...M' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

```

**Comment by carlosperate** [comment]
Hi @Polderrider 

Thank you very much for the crash report and the log! Does this problem happen every time you try to open Mu?

I believe this issue might be due to the `&` character in your username, but I am not sure why, as creating a similar user in my Windows machine doesn't trigger the same problem.

Would you be able to try this test installer to see if it works for you? It has a possible bug fix, but I'm not sure if it'll work, as I haven't been able to replicate it. If it still crashes, it would be really useful if you could add a new log copy here for debugging as well.

To download it go to the bottom of this page and click on the "mu-editor-Windows-...." link to download the test installer:
https://github.com/mu-editor/mu/actions/runs/5692107187
<img width="1110" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/8dab2f4b-1c13-447c-9f9d-2a24fbd4b5d6">

Thanks!

**Comment by carlosperate** [comment]
Hi @Polderrider, I was wondering if you were able to test that Windows installer with the fix and if that resolved your issue?

If not, you can download the latest test installer from: https://github.com/mu-editor/mu/actions/runs/7781737671
