### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by willywog** [mu-editor/crash-reports#43]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Linux 5.4.0-107-generic mu-editor/mu#121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/bob/.local/lib/python3.6/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/bob/.local/lib/python3.6/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/bob/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/bob/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/bob/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/bob/.local/share/mu/mu_venv-36-20220415-151501
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by willywog** [comment]
Yea, thank you

**Comment by carlosperate** [comment]
Great, thanks for the update!
