### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by gmansmartboy** [mu-editor/crash-reports#465]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 376, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 821, in setup
    os.makedirs(wd)
  File "C:\Users\Angela Perez\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Angela Perez\\mu_code'

```
[mu.log](https://github.com/mu-editor/crash-reports/files/11217176/mu.log)

**Comment by gmansmartboy** [comment]
Likely happened because I have multiple instances of python running on my system.
Less importantly, I have WSL2 running Debian.

**Comment by carlosperate** [comment]
Hi @gmansmartboy, thanks for the report and the log!

Looking at the log there are duplicated entries, so based on that I believe there were 2 instances of Mu running in parallel and racing each other at creating directories and installing wheels, which would be this issue: https://github.com/mu-editor/mu/issues/1755

I assume you were able to run Mu succesfully by opening again, so I'll close this as we'll release a fix for this in the next release.

Thanks again for the report, and please do reopen the issue if you are still having issue with Mu.

**Comment by gmansmartboy** [comment]
That's interesting. It started working after a an app restart.
