### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jellehbayne** [mu-editor/crash-reports#507]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.22621 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 376, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 829, in setup
    os.makedirs(images_path)
  File "C:\Users\Jia Bin\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Jia Bin\\mu_code\\images'

```

**Comment by jellehbayne** [comment]
[mu.log](https://github.com/mu-editor/crash-reports/files/11900233/mu.log)

**Comment by carlosperate** [comment]
Hi @gmansmartboy, thanks for the report and the log!

Looking at the log there are duplicated entries, so based on that I believe there were 2 instances of Mu running in parallel and racing each other at creating directories and installing wheels, which would be this issue: https://github.com/mu-editor/mu/issues/1755

I assume you were able to run Mu succesfully by opening again, so I'll close this as we'll release a fix for this in the next release.

Thanks again for the report, and please do reopen the issue if you are still having issues with Mu.
