### ISSUE TITLE
hi guys can anybody help me???:(

### ISSUE THREAD

**Issue by yafosi** [mu-editor/crash-reports#521]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 7 6.1.7601 AMD64

```
Traceback (most recent call last):
  File "C:\Users\(YASIN)\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\(YASIN)\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\(YASIN)\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Users\(YASIN)\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 699, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\(YASIN)\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 779, in ensure_interpreter_version
    raise VirtualEnv
[mu.log](https://github.com/mu-editor/crash-reports/files/12182754/mu.log)
ironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to run venv interpreter C:\Users\(YASIN)\AppData\Local\python\mu\mu_venv-38-20230727-152054\scripts\python.exe
STDERR: 'C:\Users\' is not recognized as an internal or external command,
operable program or batch file.

```
[mu.log](https://github.com/mu-editor/crash-reports/files/12182756/mu.log)

**Comment by yafosi** [comment]
im trying to program a raspberry pi pico but i can't install a compiler for that

**Comment by carlosperate** [comment]
Hi @yafosi,

Thank you very much for the crash report and the log! Does this problem happen every time you try to open Mu?

I believe this issue might be due to the `(` character in your username, but I am not sure why, as creating a similar user in my Windows machine doesn't trigger the same problem.

Would you be able to try this test installer to see if it works for you? It has a possible bug fix, but I'm not sure if it'll work, as I haven't been able to replicate it. If it still crashes, it would be really useful if you could add a new log copy here for debugging as well.

To download it go to the bottom of this page and click on the "mu-editor-Windows-...." link to download the test installer:
https://github.com/mu-editor/mu/actions/runs/5692107187
<img width="1110" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/8dab2f4b-1c13-447c-9f9d-2a24fbd4b5d6">

Thanks!

**Comment by carlosperate** [comment]
Hi @yafosi, I was wondering if you were able to test that Windows installer with the fix and if that resolved your issue?

If not, you can download the latest test installer from: https://github.com/mu-editor/mu/actions/runs/7781737671
