### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tozaki31** [mu-editor/crash-reports#523]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: ja_JP
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\tozak\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\microbit.py", line 291, in flash
    path_to_microbit, port, board_id = self.find_microbit()
  File "C:\Users\tozak\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\microbit.py", line 234, in find_microbit
    board_id = int(serial_number[:4], 16)
ValueError: invalid literal for int() with base 16: ''

```

**Comment by carlosperate** [comment]
Thanks for the report @Tozaki31!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\tozak\AppData\Local\python\mu\Logs\mu.log`

It'd be really used if you could get the DETAILS.TXT file from the MICROBIT drive and attach it here as well, as that'll have additional info to help us debug it.

Thanks!
