### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Aldoesd** [mu-editor/crash-reports#529]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 827, in create
    self.create_venv()
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\owner\AppData\Local\Programs\MUEDIT~1\Python\pythonw.exe at C:\Users\owner\AppData\Local\python\mu\mu_venv-38-20230823-205913
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\owner\\AppData\\Local\\python\\mu\\mu_venv-38-20230823-205913\\Scripts\\python.exe'

```

**Comment by Aldoesd** [comment]
Traceback (most recent call last):
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 827, in create
    self.create_venv()
  File "C:\Users\owner\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\owner\AppData\Local\Programs\MUEDIT~1\Python\pythonw.exe at C:\Users\owner\AppData\Local\python\mu\mu_venv-38-20230823-205913
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\owner\\AppData\\Local\\python\\mu\\mu_venv-38-20230823-205913\\Scripts\\python.exe'
please let me know what i need to do
