### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by 89Luka** [mu-editor/crash-reports#537]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: de_CH
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 376, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 821, in setup
    os.makedirs(wd)
  File "C:\Users\luka.brankovic\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\luka.brankovic\\mu_code'

```

**Comment by 89Luka** [comment]
gsr
