### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by qcda1** [mu-editor/crash-reports#557]
I uninstalled mu-editor (1.1.x version) and installed using pip3 install mu-editor. Installation process completer normally. Ran from menu and from command line with mu-editor. I have a working version in my download directory from the tar file as a workaround. Debian is at the latest package update.

Thanks,

Daniel.

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: fr_CA
Platform: Linux 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64

```
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.7/site-packages/mu/app.py", line 160, in run
    raise ex
  File "/home/daniel/.local/lib/python3.7/site-packages/mu/app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "/home/daniel/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "/home/daniel/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 827, in create
    self.create_venv()
  File "/home/daniel/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 865, in create_venv
    % (safe_short_path(sys.executable), self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/daniel/.local/share/mu/mu_venv-37-20231021-131206
STDERR: Usage: virtualenv.py [OPTIONS] DEST_DIR
virtualenv.py: error: no such option: --symlinks

```
[mu.log](https://github.com/mu-editor/crash-reports/files/13061357/mu.log)

**Comment by tjguk** [comment]
That's odd. We pass the `--symlinks` param when creating Mu's internal virtualenv, and we specify >=20.0 for `virtualenv` (which should be enough for `--symlinks`) in our `install_requires`.

I've just tried on a recent Linux Mint, which is an indirect Debian derivative, and it works ok.

Can you -- from within the Mu dev venv -- see what version of virtualenv you've got, eg by doing `python -m virtualenv --version` and/or see if the version you've picked up reocgnises the `--symlinks` flag?

**Comment by qcda1** [comment]
Hello. Sorry for the delay, I was out of town. Here is the result of the asked command. I wonder if I should delete all the instances of the venv-3x… directories… I didn’t see this building...

Best regards,

Daniel.

From a terminal:
***@***.***:~$ python -m virtualenv --version
virtualenv 20.13.1 from /home/daniel/.local/lib/python3.7/site-packages/virtualenv/__init__.py
***@***.***:~$

From one of the venv I found for mu:
***@***.***:~$ find -name activate
./devel/midnite/midnitev/bin/activate
./devel/monitormidnite/monmidnite/bin/activate
./.local/share/mu/mu_venv-37-20220206-173844.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-37-20231021-130902/bin/activate
./.local/share/mu/mu_venv-38-20231021-112740.FAILED/bin/activate
./.local/share/mu/mu_venv-37-20231021-130902.FAILED/bin/activate
./.local/share/mu/mu_venv-37-20220206-110931.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-37-20220206-173359.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-37-20220206-110051.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-37-20231021-112447.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-37-20220206-174042.SUPERSEDED/bin/activate
./.local/share/mu/mu_venv-38-20231021-112209.FAILED/bin/activate
./Backups/midnite/midnitev/bin/activate
./Backups/pymagnum/magnumv/bin/activate
./Backups/monitormidnite/monmidnite/bin/activate
./Backups/rasp02pi/base/bin/activate
./.platformio/penv/bin/activate
***@***.***:~$ source ./.local/share/mu/mu_venv-38-20231021-112740.FAILED/bin/activate
(mu_venv-38-20231021-112740) ***@***.***:~$ python -m virtualenv --version
virtualenv 20.13.1 from /home/daniel/.local/lib/python3.7/site-packages/virtualenv/__init__.py
(mu_venv-38-20231021-112740) ***@***.***:~$






Le 21 oct. 2023 à 13:54, Tim Golden ***@***.******@***.***>> a écrit :

python -m virtualenv --version
