### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by alpierce** [mu-editor/crash-reports#562]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/__main__.py", line 9, in <module>
    main()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/__main__.py", line 5, in main
    run()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 376, in run
    editor.setup(setup_modes(editor, editor_window))
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/logic.py", line 846, in setup
    os.makedirs(music_path)
  File "/Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/Volumes/CIRCUITPY/music'

```
[mu.log](https://github.com/mu-editor/crash-reports/files/13210465/mu.log)

**Comment by alpierce** [comment]
Crashes on launch, recent problem.

**Comment by alpierce** [comment]
Seems to be trying to load a bogus volume

**Comment by alpierce** [comment]
OSError: [Errno 28] No space left on device: '/Volumes/CIRCUITPY/music'

**Comment by alpierce** [comment]
Mu loads and runs after I unmounted the CIRCUITPY volume, which had no music folder to begin with.??
