### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DrDarby** [mu-editor/crash-reports#583]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.22621 AMD64

```
Traceback (most recent call last):
  File "C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 637, in ensure_and_create
    self.create()
  File "C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 827, in create
    self.create_venv()
  File "C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 863, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\sulpi\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\sulpi\AppData\Local\python\mu\mu_venv-38-20231217-094330
OSError: [Errno 28] No space left on device

```
[mu.log](https://github.com/mu-editor/crash-reports/files/13697424/mu.log)

**Comment by carlosperate** [comment]
Hi @DrDarby,

Based on the error it looks like maybe you are running out of hard drive space on your computer. If you free up some space and try again, does that work?
