### ISSUE TITLE
Mu Crash Report

### ISSUE THREAD

**Issue by dan1977smith** [mu-editor/crash-reports#603]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_AU
Platform: Windows 10 10.0.22621 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Dan&Bel\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Users\Dan&Bel\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Dan&Bel\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Users\Dan&Bel\AppData\Local\Pr
[mu.log](https://github.com/mu-editor/crash-reports/files/13999616/mu.log)
[mu.log](https://github.com/mu-editor/crash-reports/files/13999618/mu.log)
ograms\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 699, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\Dan&Bel\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 779, in ensure_interpreter_version
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to run venv interpreter C:\Users\Dan&Bel\AppData\Local\python\mu\mu_venv-38-20240121-113302\scripts\python.exe
STDERR: 'C:\Users\Dan' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

```

**Comment by carlosperate** [comment]
Hi @dan1977smith, thanks for the report!

I think we've fixed this issue in the project, but  haven't made a release yet with the fix.

Could you try the Windows installer from this page to check if it works with the latest test version? (you need to be logged into GitHub to be able to download the file)
https://github.com/mu-editor/mu/actions/runs/7781737671

<img width="1175" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/06fe07d3-cc97-4d71-882c-e9b203c58aa3">

**Comment by carlosperate** [comment]
Hi @dan1977smith, I was wondering if you were able to test that Windows installer with the fix and if that resolved your issue?
