### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by LYCNTU** [mu-editor/crash-reports#605]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: zh_TW
Platform: Windows 10 10.0.19044 AMD64

```
\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Users\USER\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 701, in ensure
    self.ensure_key_modules()
  File "C:\Users\USER\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 806, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\python\mu\mu_venv-38-20240124-145837\lib\site-packages\flask\__init__.py", line 3, in <module>
    from werkzeug.exceptions import abort as abort
  File "C:\Users\USER\AppData\Local\python\mu\mu_venv-38-20240124-145837\lib\site-packages\werkzeug\__init__.py", line 1, in <module>
    from .serving import run_simple as run_simple
  File "C:\Users\USER\AppData\Local\python\mu\mu_venv-38-20240124-145837\lib\site-packages\werkzeug\serving.py", line 17, in <module>
    import socket
  File "C:\Users\USER\AppData\Local\Programs\MUEDIT~1\Python\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python312.dll conflicts with this version of Python.

```

**Comment by carlosperate** [comment]
Hi @LYCNTU, thanks for the report!

I think the issue is that Flask 2 needs Werkzeug 2, and by default it installed the latest (v3). We've added a fix to the codebase, but haven't made a release yet: https://github.com/mu-editor/mu/pull/2465

Would you be able to test the latest test installer to see if it fixes the issue for you?

You need to be logged into GitHub to be able to download the file:
https://github.com/mu-editor/mu/actions/runs/7781737671
<img width="1080" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/56a66f53-0931-447f-b287-5d8d1a4b3191">
