### ISSUE TITLE
MU-Editor does not start with python 3.81rc1

### ISSUE THREAD

**Issue by JeanMichelGarcia** [mu-editor/crash-reports#619]
[mu.log](https://github.com/mu-editor/crash-reports/files/14315878/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: fr_FR
Platform: Windows 10 10.0.22000 AMD64

```
line 661, in ensure_and_create
    self.ensure()
  File "c:\program files\python38\lib\site-packages\mu\virtual_environment.py", line 701, in ensure
    self.ensure_key_modules()
  File "c:\program files\python38\lib\site-packages\mu\virtual_environment.py", line 806, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\jean-michel\AppData\Local\python\mu\mu_venv-38-20240216-214032\lib\site-packages\flask\__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "D:\Users\jean-michel\AppData\Local\python\mu\mu_venv-38-20240216-214032\lib\site-packages\flask\app.py", line 28, in <module>
    from . import cli
  File "D:\Users\jean-michel\AppData\Local\python\mu\mu_venv-38-20240216-214032\lib\site-packages\flask\cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "D:\Users\jean-michel\AppData\Local\python\mu\mu_venv-38-20240216-214032\lib\site-packages\flask\helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (D:\Users\jean-michel\AppData\Local\python\mu\mu_venv-38-20240216-214032\lib\site-packages\werkzeug\urls.py)

```

**Comment by carlosperate** [comment]
Hi @JeanMichelGarcia, thanks for the report!

I think the issue is that Flask 2 needs Werkzeug 2, and by default it installed the latest (v3). We've added a fix to the codebase, but haven't made a release yet: https://github.com/mu-editor/mu/pull/2465

Would you be able to test the latest test installer to see if it fixes the issue for you?

You need to be logged into GitHub to be able to download the file:
https://github.com/mu-editor/mu/actions/runs/7781737671
<img width="1080" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/56a66f53-0931-447f-b287-5d8d1a4b3191">

**Comment by JeanMichelGarcia** [comment]
Hi @carlosperate 
mu 1.2.2 for windows 64 is installing right
The problem is the pip  install still 1.2.0 and not running with the error i sent

**Comment by carlosperate** [comment]
> mu 1.2.2 for windows 64 is installing right

Are you able to run Mu 1.2.2 after installing it? Or does it show the same error?

**Comment by JeanMichelGarcia** [comment]
It’s running when by windows installer installed !!

 

De : Carlos Pereira Atencio ***@***.***> 
Envoyé : lundi 4 mars 2024 11:56
À : mu-editor/crash-reports ***@***.***>
Cc : JeanMichelGarcia ***@***.***>; Mention ***@***.***>
Objet : Re: [mu-editor/crash-reports] MU-Editor does not start with python 3.81rc1 (Issue #619)

 

mu 1.2.2 for windows 64 is installing right

Are you able to run Mu 1.2.2 after installing it? Or does it show the same error?

**Comment by carlosperate** [comment]
Thanks for confirming @JeanMichelGarcia, I'm glad the fix works for you.

Once we make the v1.2.2 release you should be able to pip install it as well.

In the meantime, you can probably pip install Mu via git url:
```
pip install git+https://github.com/mu-editor/mu.git
```

**Comment by JeanMichelGarcia** [comment]
Thanks for the tip. I will try asap

BR

 

De : Carlos Pereira Atencio ***@***.***> 
Envoyé : mardi 5 mars 2024 15:54
À : mu-editor/crash-reports ***@***.***>
Cc : JeanMichelGarcia ***@***.***>; Mention ***@***.***>
Objet : Re: [mu-editor/crash-reports] MU-Editor does not start with python 3.81rc1 (Issue #619)

 

Thanks for confirming @JeanMichelGarcia <https://github.com/JeanMichelGarcia> , I'm glad the fix works for you.

Once we make the v1.2.2 release you should be able to pip install it as well.

In the meantime, you can probably pip install Mu via git url:

pip install git+https://github.com/mu-editor/mu.git
