### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by APearsonOCAT** [mu-editor/crash-reports#624]
Software installed via Intune management. MU runs fine when i log on as myself (admin) but as a regular user, this error occurred. 
[mu.log](https://github.com/mu-editor/crash-reports/files/14460308/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_GB
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\app.py", line 160, in run
    raise ex
  File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\app.py", line 147, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 661, in ensure_and_create
    self.ensure()
  File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 699, in ensure
    self.ensure_interpreter_version()
  File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 779, in ensure_interpreter_version
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to run venv interpreter C:\Users\TestStaff(TSS)\AppData\Local\python\mu\mu_venv-38-20240301-110406\scripts\python.exe
STDERR: 'C:\Users\TestStaff' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by carlosperate** [comment]
Thanks for the repor @APearsonOCAT!

I think this might be fixed in the project, but not yet released. Could you try the latest test installer to see if that version works for you?

You need to be logged into GitHub to be able to download the file:
https://github.com/mu-editor/mu/actions/runs/7781737671
<img width="1080" alt="image" src="https://github.com/mu-editor/crash-reports/assets/4189262/56a66f53-0931-447f-b287-5d8d1a4b3191">

**Comment by APearsonOCAT** [comment]
Thanks Carlos, I will give that a try.

**Comment by APearsonOCAT** [comment]
Just tried version 1.2.2. I still get an error. I assume it is the same one:

Traceback (most recent call last):
File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\app.py", line 162, in run
raise ex
File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\app.py", line 149, in run
venv.ensure_and_create(self.display_text)
File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 692, in ensure_and_create
self.ensure()
File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 732, in ensure
self.ensure_interpreter_version()
File "C:\Program Files (x86)\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 812, in ensure_interpreter_version
raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to run venv interpreter C:\Users\TestStaff(TSS)\AppData\Local\python\mu\mu_venv-38-20240304-101536\scripts\python.exe
STDERR: 'C:\Users\TestStaff' is not recognized as an internal or external command,
operable program or batch file.
[mu (1).log](https://github.com/mu-editor/crash-reports/files/14480154/mu.1.log)

**Comment by APearsonOCAT** [comment]
I'm guessing it might be a permissions issue? I am an admin, but TestStaff(TSS) is a regular user. They can run the main exe, but the issue occurs I assume, when it is copying or running files from within the user profile, 'C:\Users\TestStaff\
