### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by edmengak** [mu-editor/crash-reports#705]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\jean\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 1224, in keyPressEvent
    self.parse_input(key, text, modifiers)
  File "C:\Users\jean\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 1273, in parse_input
    os.kill(pid, signal.SIGINT)
PermissionError: [WinError 5] Access is denied

```

**Comment by edmengak** [comment]
[mu.log](https://github.com/user-attachments/files/17353317/mu.log)

**Comment by edmengak** [comment]
Don't know if I did this correctly.
