### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by shivansh4123** [mu-editor/crash-reports#738]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.2
Locale: en_IN
Platform: Windows 10 10.0.22621 AMD64

```
Traceback (most recent call last):
  File "C:\Users\shiva\mu\mu\app.py", line 162, in run
    raise ex
  File "C:\Users\shiva\mu\mu\app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\shiva\mu\mu\virtual_environment.py", line 668, in ensure_and_create
    self.create()
  File "C:\Users\shiva\mu\mu\virtual_environment.py", line 861, in create
    self.install_baseline_packages()
  File "C:\Users\shiva\mu\mu\virtual_environment.py", line 978, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "C:\Users\shiva\mu\mu\wheels\__init__.py", line 206, in download
    pip_download(temp_dirpath, logger, extra_pip_flags)
  File "C:\Users\shiva\mu\mu\wheels\__init__.py", line 140, in pip_download
    "Pip was unable to download %s" % pip_identifiers
TypeError: not all arguments converted during string formatting

```

**Comment by shivansh4123** [comment]
i found out how to solve this , in the wheels module (wheels/__init__.py), locate the pip_download function. The line that raises the the error is: "Pip was unable to download %s" % pip_identifiers and Modify it to ensure proper string formatting: "Pip was unable to download {}".format(pip_identifiers)
