### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Roswick** [mu-editor/crash-reports#740]
[mu.log.2024-12-16.txt](https://github.com/user-attachments/files/18156264/mu.log.2024-12-16.txt)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.2.0
Locale: en_US
Platform: Windows 10 10.0.19045 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Roz Works\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 165, in <lambda>
    remaining_task = lambda commands=remainder: self.execute(commands)
  File "C:\Users\Roz Works\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 163, in execute
    self.write(command)
  File "C:\Users\Roz Works\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 149, in write
    self.serial.write(data)
AttributeError: 'NoneType' object has no attribute 'write'

```

**Comment by Roswick** [comment]
I just loaded a new version of Mu.
No control of the PICO after hitting run short of unplugging it.
Locked out of saving my file.
Cannot stop the file running in the REPL.
After the crash, Mu icon no longer on desktop.
Deleted Mu from my computer then reloaded the new version. Behavior repeated itself.
