### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by fruitpie999** [mu-editor/crash-reports#78]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 10 10.0.14393 AMD64

```
Traceback (most recent call last):
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 522, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 573, in ensure_interpreter_version
    ok, output = self.run_subprocess(
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 373, in run_subprocess
    process = subprocess.run(
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\breud\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid
```

**Comment by fruitpie999** [comment]
v1.1.1 installs ok now - thank for all your hard work
