### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dkjrivero** [mu-editor/crash-reports#80]
**REMEMBER TO ATTACH YOUR LOG FILE**

[mu.log](https://github.com/mu-editor/mu/files/7228953/mu.log)

Version: 1.1.0.beta.5
Locale: en_US
Platform: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

```
entCreateError: Unable to create a virtual environment using /Applications/Mu Editor.app/Contents/MacOS/../Resources/Python/bin/python3.8 at /Users/dominiquer/Library/Application Support/mu/mu_venv-38-20210924-181437
RuntimeError: failed to build image pip because:
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 46, in install
    for name, module in self._console_scripts.items():
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 131, in _console_scripts
    entry_points = self._dist_info / "entry_points.txt"
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 118, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at /Users/dominiquer/Library/Application Support/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-21.2.4-py3-none-any, has pip

```

**Comment by carlosperate** [comment]
@dkjrivero I believe this fix to this has been released with Mu v1.1.1. Would you be able to test the latest installer from https://codewith.mu/en/download and see if it works in your environment? Thanks
